services:
  db:
    image: postgres:17.6-alpine3.21
    env_file:
      - path: ./base.env
        required: true
      - path: ./override.env
        required: false
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - path: ./base.env
        required: true
      - path: ./override.env
        required: false

volumes:
  postgres_data:
