[project]
name = "shortr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=5.2.6",
    "django-types>=0.22.0",
    "psycopg2-binary>=2.9.10",
    "sqids>=0.5.2",
]
