# Generated by Django 5.2.6 on 2025-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=2048)),
            ],
        ),
    ]
